name: "Design Studio on 4TH MAIN"
description: "Projects by 4th Main"

url: "http://localhost:4000"
#url: "http://4thmain.github.io"

projects: ./_projects

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
